- ip: 172.16.255.1
  usage: Route Collector
  asn: 4211110101
- ip: 172.16.255.2
  usage: ACME Server
  asn: 4220084444
- ip: 172.16.255.53
  usage: DNS
  asn:
    - 4211110114
    - 4211112243
    - 4211114613
    - 4220081816
    - 4220081919
    - 4220084444
