name: Generator

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'as/**'
      - 'script/**'

concurrency:
  group: generator
  cancel-in-progress: true

jobs:
  generator:
    runs-on: ubuntu-latest
    name: Generator
    steps:
      - name: Setup Python Environment
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Run Generator
        run: |
          pip3 install pyyaml IPy py-markdown-table requests
          python3 script/generator.py
      - name: Upload Metadata to GitHub
        run: |
          cd metadata-repo
          git init
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add *
          git commit -m "Sync"
          git branch -M main
          git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/hdu-dn11/metadata.git
          git push --force -u origin main
      - name: Upload Monitor-Metadata to COS
        timeout-minutes: 5
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: 'monitor-metadata'
          remote_path: 'as'
          clean: true
