on:
  push:
    branches:
      - main

jobs:
  generator:
    runs-on: ubuntu-latest
    name: Generator
    steps:
      - name: Setup Python Environment
        uses: actions/setup-python@main
        with:
          python-version: "3.10"
      - name: Checkout Code
        uses: actions/checkout@main
      - name: Run Generator
        run: |
          pip3 install pyyaml IPy py-markdown-table requests
          python3 script/generator.py
      - name: Upload Monitor-Metadata to COS
        timeout-minutes: 5
        uses: TencentCloud/cos-action@v1
        with:
          secret_id: ${{ secrets.TENCENT_CLOUD_SECRET_ID }}
          secret_key: ${{ secrets.TENCENT_CLOUD_SECRET_KEY }}
          cos_bucket: ${{ secrets.COS_BUCKET }}
          cos_region: ${{ secrets.COS_REGION }}
          local_path: 'monitor-metadata'
          remote_path: 'as'
          clean: true
      - name: Upload Metadata to GitHub
        run: |
          mkdir metadata
          cd metadata
          git init
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          mv ../dn11_roa_bird2.conf .
          mv ../dn11.zone .
          mv ../README.md .
          git add dn11_roa_bird2.conf dn11.zone README.md
          git commit -m "Sync"
          git branch -M main
          git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/hdu-dn11/metadata.git
          git push --force -u origin main
